weights: C:\hardhat\yolov5-master\runs\train\exp20\weights\best220517.pt
cfg: ''
data: C:\hardhat\yolov5-master\data\coco128.yaml
hyp: yolov5-master\data\hyps\hyp.scratch-low.yaml
epochs: 50
batch_size: 16
imgsz: 416
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
noplots: false
evolve: null
bucket: ''
cache: ram
image_weights: false
device: ''
multi_scale: false
single_cls: false
optimizer: SGD
sync_bn: false
workers: 2
project: yolov5-master\runs\train
name: exp
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0.0
patience: 100
freeze:
- 0
save_period: -1
local_rank: -1
entity: null
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
save_dir: yolov5-master\runs\train\exp23
